namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: prod
  helm:
    values:
      replication: false
      imageName: alphabravoio/hello-world:latest
  clusterSelector:
    matchLabels:
      env: prod

